---
- name: Pull Docker Image from Docker Hub and Run Container
  hosts: localhost
  connection: local
  remote_user: ziyaurraheman
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "calci_pro"
        source: pull
        api_version: auto
        timeout: 60
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Gather Docker service facts
      command: systemctl is-active docker
      register: docker_service_status
      ignore_errors: true

    - name: Start Docker service (if not already running)
      service:
        name: docker
        state: started
      when: docker_service_status.stdout != 'active'

    - name: Pull Docker Image Locally
      command: docker pull calci_pro

    - name: Run Docker container
      docker_container:
        name: calci_pro
        image: calci_pro
        state: started
        interactive: false
        detach: true
