---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  connection: local
  remote_user: ziyaurraheman
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "calci_pro"
        source: pull
        api_version: auto
        timeout: 60
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Gather Docker service facts
      service_facts:
        gather_facts: no

    - name: Start Docker service (if not already running)
      service:
        name: docker
        state: started
      when: "'docker' in ansible_facts.services and ansible_facts.services['docker'].state != 'running'"

    - name: Run Docker container
      docker_container:
        name: calci_pro
        image: calci_pro
        state: started
        interactive: false
        detach: true
