---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  connection: local
  remote_user: ziyaurraheman
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "calci_pro"
        source: pull
        api_version: auto
        timeout: 60
      register: docker_pull_result
      ignore_errors: true

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Gather Docker service facts
      command: systemctl is-active docker
      register: docker_service_status
      ignore_errors: true

    - name: Start Docker service (if not already running)
      service:
        name: docker
        state: started
      when: docker_service_status.stdout != 'active'

    - name: Handle Docker image pull errors
      block:
        - name: Pull Docker image to local
          command: docker pull calci_pro
      rescue:
        - name: Display error message
          debug:
            msg: "Failed to pull the Docker image. Check if the image exists, and ensure proper permissions and authentication."
