---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: ziyaurraheman
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "calci_pro"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started
      when: ansible_facts['os_family'] == "Debian"

    - name: Running container
      shell: /usr/bin/docker run -it -d --name calci_pro calci_pro
      # Add ansible_ssh_port if SSH is running on a non-default port
